version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: martiello_app
    ports:
      - "5009:5000"  # Porta do host (5009) mapeada para o container (5000)
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__MongoDb=mongodb://root:example@mongo:27017
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: martiello_mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: