apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  labels:
    app: martiello-api
data:
  # Configurações do ambiente
  ASPNETCORE_ENVIRONMENT: "Development"
  DOTNET_RUNNING_IN_CONTAINER: "true"
  # URL base da API
  ASPNETCORE_URLS: "http://+:5000"
  # Nome do banco de dados
  DatabaseName: "Martiello"
  # Configurações do processamento de pedidos
  OrderProcessing__UseProcessing: "false"
  OrderProcessing__UseRealTimePreparation: "false"
  OrderProcessing__CheckIntervalInSeconds: "30"
