apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: martiello-cluster
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
