apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  # Tipo do serviço - ClusterIP pois o MongoDB só precisa ser acessível internamente
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongodb
  # Seletor para identificar os pods do MongoDB
  selector:
    app: mongodb
