apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: mongodb
type: Opaque
stringData:
  # Credenciais do usuário root
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: example
  # String de conexão para a API
  connection-string: mongodb://root:example@mongodb-service:27017
