apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  serviceName: mongodb-service
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0
          ports:
            - containerPort: 27017
              name: mongodb
          # Recursos do container
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          # Variáveis de ambiente do MongoDB
          envFrom:
            - configMapRef:
                name: mongodb-config
            - secretRef:
                name: mongodb-secret
          # Volume para dados
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      # Usando emptyDir em vez de PVC temporariamente
      volumes:
        - name: mongodb-data
          emptyDir: {}
